# Generated by Django 4.0 on 2021-12-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='id',
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='class_app.assignment'),
        ),
    ]
