# Generated by Django 4.0 on 2022-01-07 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_alter_class_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='class_app.userprofile'),
        ),
    ]
