# Generated by Django 4.0 on 2022-01-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0007_student_emergency_contact_number1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_grade',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
